spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create   # update
logging:
  level:
    org:
      springframework: INFO
response:
  message:
    url: http://my-app-pastebin.home/
    is_empty: No paste records
    expired: The paste has expired
    records_size: 10