spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create   # update